version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 783764594790.dkr.ecr.us-east-1.amazonaws.com)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t kumar-flask-app .
      - docker tag kumar-flask-app:latest 783764594790.dkr.ecr.us-east-1.amazonaws.com/kumar-flask-app:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 783764594790.dkr.ecr.us-east-1.amazonaws.com/kumar-flask-app:latest

artifacts:
  files:
    - '**/*'
