name: Deploy to AWS ECR

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Build & Push Docker image to ECR
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.ECR_REPO_URI }}:latest .

    - name: Push to Amazon ECR
      run: |
        docker push ${{ secrets.ECR_REPO_URI }}:latest
